module.exports = {
  MODELS_LIST: 'models:list',
  MODELS_REFRESH: 'models:refresh',
  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',
  CONNECTION_TEST: 'connection:test',
  CONVERSATIONS_LIST: 'conversations:list',
  CONVERSATIONS_CREATE: 'conversations:create',
  CONVERSATIONS_READ: 'conversations:read',
  CONVERSATIONS_UPDATE: 'conversations:update',
  CONVERSATIONS_DELETE: 'conversations:delete',
  CHAT_SEND: 'chat:send',
  CHAT_CANCEL: 'chat:cancel',
  CHAT_CHUNK: 'chat:chunk',
  CHAT_COMPLETE: 'chat:complete',
  CHAT_ERROR: 'chat:error',
  COMPANION_OPEN: 'companion:open',
  COMPANION_PIN: 'companion:set-always-on-top',
  CONTEXT_ATTACH: 'context:attach',
  CONTEXT_REMOVE: 'context:remove',
  SHELL_OPEN_EXTERNAL: 'shell:open-external',
};
